# Generated by Django 3.0.2 on 2020-10-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
