# Generated by Django 3.0.2 on 2020-10-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_category', '0002_auto_20201028_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='test_category')),
                ('country', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('sku', models.CharField(max_length=100)),
                ('partNumber', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('compareAtPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_category.Brands')),
                ('categories', models.ManyToManyField(related_name='reverse_categories', to='test_category.Categories')),
            ],
            options={
                'verbose_name': 'Товар',
            },
        ),
    ]
