# Generated by Django 3.0.2 on 2020-10-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_category', '0003_brands_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compareAtPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='partNumber',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='brands',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
