# Generated by Django 3.0.2 on 2020-11-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_category', '0007_auto_20201102_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriestree',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_reverse', to='test_category.ProductTwo'),
        ),
        migrations.AlterField(
            model_name='categoriestree',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
