# Generated by Django 3.0.2 on 2020-11-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_category', '0012_categories_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='layout',
            field=models.CharField(default='products', max_length=30),
        ),
    ]
