# Generated by Django 3.0.2 on 2020-11-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_category', '0014_country_engine_makes_vehicle_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='test_category.Engine'),
        ),
    ]
