# Generated by Django 3.0.2 on 2020-11-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_category', '0017_auto_20201105_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='fuel',
            field=models.CharField(choices=[('D', 'Desel'), ('G', 'Gasoline')], default='D', max_length=10),
        ),
        migrations.AlterField(
            model_name='engine',
            name='volume',
            field=models.CharField(choices=[('3', '3.0'), ('3.5', '3.5'), ('2.5', '2.5'), ('2', '2.0'), ('1.5', '1.5')], default='2.5', max_length=10),
        ),
    ]
