# Generated by Django 3.0.2 on 2020-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_category', '0019_uservehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
