# Generated by Django 3.0.2 on 2021-05-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210528_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='image',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
