# Generated by Django 3.0.2 on 2021-05-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210530_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='slug',
        ),
    ]
