# Generated by Django 3.0.2 on 2021-09-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210530_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.CharField(choices=[('onGet', 'ПРИ ПОЛУЧЕНИИ'), ('onLine', 'ОНЛАЙН')], default='onGet', max_length=50),
        ),
    ]
