# Generated by Django 3.0.2 on 2021-09-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210916_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.CharField(choices=[('self', 'САМОВЫВОЗ'), ('kur', 'КУРЬЕРОМ'), ('post', 'ТРАНСПОРТНОЙ КОМПАНИЕЙ')], default='self', max_length=50),
        ),
    ]
