# Generated by Django 3.0.2 on 2021-11-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210917_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='product_cat_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='product_one_c_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
