# Generated by Django 3.0.2 on 2021-04-23 09:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('textHtml', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
