# Generated by Django 3.0.2 on 2021-04-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companypages',
            options={'verbose_name': 'Страницa Компании', 'verbose_name_plural': 'Страницы Компании'},
        ),
        migrations.AddField(
            model_name='companypages',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
