# Generated by Django 3.0.2 on 2021-04-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_pages', '0002_auto_20210423_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypages',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
