# Generated by Django 3.0.2 on 2021-04-23 10:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_pages', '0003_auto_20210423_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypages',
            name='textHtml',
        ),
        migrations.AddField(
            model_name='companypages',
            name='textHTML',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
