# Generated by Django 3.0.2 on 2020-02-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20200207_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='angpricesall',
            options={'managed': True},
        ),
    ]
