# Generated by Django 3.0.2 on 2020-02-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20200210_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='angpricesall',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='SuppliersBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.AngSuppliers')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
