# Generated by Django 3.0.2 on 2020-02-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_auto_20200214_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersbrands',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
