# Generated by Django 3.0.2 on 2020-03-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_suppliersbrands_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliersbrands',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_related', to='brands.AngSuppliers'),
        ),
    ]
