# Generated by Django 3.0.2 on 2020-10-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_auto_20200312_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandsDictSup',
        ),
    ]
