# Generated by Django 3.0.2 on 2020-10-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_delete_brandsdictsup'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsdict',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='brandsdict',
            name='country_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
