# Generated by Django 3.0.2 on 2020-10-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_auto_20201028_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsdict',
            name='image',
            field=models.ImageField(blank=True, upload_to='brands'),
        ),
        migrations.AddField(
            model_name='brandsdict',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
