# Generated by Django 3.0.2 on 2021-03-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_auto_20201028_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsdict',
            name='original',
            field=models.BooleanField(default=False),
        ),
    ]
