# Generated by Django 3.0.2 on 2020-03-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.CarModel'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category_reverse', to='product.Category'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='unit',
            field=models.CharField(default='шт', max_length=10),
        ),
    ]
