# Generated by Django 3.0.2 on 2020-03-12 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200312_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_product_related_+', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Units'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.CarEngine'),
        ),
    ]
