# Generated by Django 3.0.2 on 2020-03-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200313_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductThumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img150', models.ImageField(blank=True, max_length=255, null=True, upload_to='dummy')),
                ('img245', models.ImageField(blank=True, max_length=255, null=True, upload_to='dummy')),
                ('img500', models.ImageField(blank=True, max_length=255, null=True, upload_to='dummy')),
                ('img800', models.ImageField(blank=True, max_length=255, null=True, upload_to='dummy')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.ProductImage')),
            ],
        ),
    ]
