# Generated by Django 3.0.2 on 2020-03-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productthumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute',
            new_name='attribute_name',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_value',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
