# Generated by Django 3.0.2 on 2020-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200313_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='one_c_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
