# Generated by Django 3.0.2 on 2020-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200314_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='engine',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine',
            field=models.ManyToManyField(blank=True, to='product.CarEngine'),
        ),
    ]
