# Generated by Django 3.0.2 on 2020-03-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engine',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.CarEngine'),
            preserve_default=False,
        ),
    ]
