# Generated by Django 3.0.2 on 2020-03-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_engine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='unit',
            new_name='unit_name',
        ),
    ]
