# Generated by Django 3.0.2 on 2020-03-21 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20200317_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideos',
            name='title',
        ),
        migrations.AddField(
            model_name='productvideos',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='carengine',
            name='name',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Country'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.ManyToManyField(blank=True, related_name='car_engine', to='product.CarEngine'),
        ),
    ]
