# Generated by Django 3.0.2 on 2020-03-21 17:07

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200321_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='img150',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.img_path_tmb),
        ),
        migrations.AddField(
            model_name='productimage',
            name='img245',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.img_path_tmb),
        ),
        migrations.AddField(
            model_name='productimage',
            name='img500',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.img_path_tmb),
        ),
        migrations.AddField(
            model_name='productimage',
            name='img800',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.img_path_tmb),
        ),
    ]
