# Generated by Django 3.0.2 on 2020-03-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200321_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductThumb',
        ),
    ]
