# Generated by Django 3.0.2 on 2020-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20200325_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='car_model',
        ),
        migrations.AddField(
            model_name='product',
            name='car_model',
            field=models.ManyToManyField(related_name='model_product', to='product.CarModel'),
        ),
    ]
