# Generated by Django 3.0.2 on 2020-03-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20200326_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='engine',
        ),
        migrations.AddField(
            model_name='product',
            name='engine',
            field=models.ManyToManyField(related_name='car_related_engine', to='product.CarEngine'),
        ),
    ]
