# Generated by Django 3.0.2 on 2020-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='full_minus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='full_plus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
