# Generated by Django 3.0.2 on 2020-04-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20200402_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='old_group_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keywords',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_category', to='product.Category'),
        ),
    ]
