# Generated by Django 3.0.2 on 2020-04-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20200402_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsMinus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minus', models.CharField(blank=True, max_length=100, null=True)),
                ('full_minus', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_category_minus', to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordsPlus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus', models.CharField(blank=True, max_length=100, null=True)),
                ('full_plus', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_category', to='product.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
    ]
