# Generated by Django 3.0.2 on 2020-04-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20200402_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordsplus',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='full_minus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='full_plus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='minus',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='category',
            name='plus',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='KeywordsMinus',
        ),
        migrations.DeleteModel(
            name='KeywordsPlus',
        ),
    ]
