# Generated by Django 3.0.2 on 2020-04-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20200406_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='category_tags', to='product.CategoryTags'),
        ),
    ]
