# Generated by Django 3.0.2 on 2020-04-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20200409_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_name',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.ProductAttributeName'),
            preserve_default=False,
        ),
    ]
