# Generated by Django 3.0.2 on 2020-04-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20200411_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='name',
            new_name='attribute_name',
        ),
    ]
