# Generated by Django 3.0.2 on 2020-04-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_auto_20200412_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cross',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_cross', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='one_c_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
