# Generated by Django 3.0.3 on 2020-06-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20200421_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='cross',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_cross', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='product.Product', verbose_name='Относится к Товару'),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_description', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='productvideos',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_video', to='product.Product'),
        ),
    ]
