# Generated by Django 3.0.3 on 2020-07-24 12:20

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_productimage_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='img150x150',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.img_path_tmb),
        ),
        migrations.AddField(
            model_name='productimage',
            name='img245x245',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.img_path_tmb),
        ),
        migrations.AddField(
            model_name='productimage',
            name='img500x500',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.img_path_tmb),
        ),
        migrations.AddField(
            model_name='productimage',
            name='img800x800',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.img_path_tmb),
        ),
    ]
