# Generated by Django 3.0.2 on 2020-10-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_auto_20200724_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atr_name', to='product.ProductAttributeName'),
        ),
    ]
