# Generated by Django 3.0.2 on 2021-03-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_auto_20210313_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Годы',
            },
        ),
        migrations.AddField(
            model_name='carmake',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='year_from', to='product.Years'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='year_to', to='product.Years'),
        ),
    ]
