# Generated by Django 3.0.2 on 2021-03-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_auto_20210313_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
