# Generated by Django 3.0.2 on 2021-03-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_delete_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmake',
            name='priority',
            field=models.CharField(blank=True, choices=[('HIGEST', 'HIGEST'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('LOWEST', 'LOWEST')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('HIGEST', 'HIGEST'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('LOWEST', 'LOWEST')], max_length=10, null=True),
        ),
    ]
