# Generated by Django 3.0.2 on 2021-03-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_auto_20210315_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='carengine',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
