# Generated by Django 3.0.2 on 2021-03-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_carengine_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='priority',
            field=models.CharField(blank=True, choices=[('HIGEST', 'HIGEST'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('LOWEST', 'LOWEST')], default='LOWEST', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('HIGEST', 'HIGEST'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('LOWEST', 'LOWEST')], default='LOWEST', max_length=100, null=True),
        ),
    ]
