# Generated by Django 3.0.2 on 2021-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_auto_20210315_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmake',
            name='rusname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='rusname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
