# Generated by Django 3.0.2 on 2021-03-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Store'),
        ),
    ]
