# Generated by Django 3.0.2 on 2021-03-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_auto_20210315_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.RemoveField(
            model_name='price',
            name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
