# Generated by Django 3.0.2 on 2021-03-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_auto_20210316_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbages',
            name='name',
            field=models.CharField(blank=True, choices=[('SALE', 'РАСПРОДАЖА'), ('NEW', 'НОВИНКА')], max_length=20, null=True),
        ),
    ]
