# Generated by Django 3.0.2 on 2021-03-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_auto_20210316_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
