# Generated by Django 3.0.2 on 2021-03-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_auto_20210316_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[(5, 'HIGEST'), (4, 'HIGH'), (3, 'MEDIUM'), (2, 'LOW'), (1, 'LOWEST')], default=1, max_length=100, null=True),
        ),
    ]
