# Generated by Django 3.0.2 on 2021-03-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_auto_20210325_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(5, 'Higest'), (4, 'High'), (3, 'Medium'), (2, 'Low'), (1, 'Lowest')], default=1, null=True),
        ),
    ]
