# Generated by Django 3.0.2 on 2021-04-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0072_auto_20210325_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, default='new', max_length=20, null=True),
        ),
    ]
