# Generated by Django 3.0.2 on 2021-04-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='carengine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cars'),
        ),
        migrations.AddField(
            model_name='carmake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cars'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cars'),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(default=None, upload_to='images/cars'),
            preserve_default=False,
        ),
    ]
