# Generated by Django 3.0.2 on 2021-04-18 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_auto_20210417_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrating',
            options={'verbose_name': 'Рейтинг'},
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.ProductRating'),
        ),
    ]
