# Generated by Django 3.0.2 on 2021-04-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_auto_20210418_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratingQuantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
