# Generated by Django 3.0.2 on 2021-04-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_auto_20210418_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
    ]
