# Generated by Django 3.0.2 on 2021-04-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0083_auto_20210418_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_bages', to='product.Product'),
        ),
    ]
