# Generated by Django 3.0.2 on 2021-06-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_auto_20210423_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='availability_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='store',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_stock', to='product.Store'),
        ),
    ]
