# Generated by Django 3.0.2 on 2021-06-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0086_auto_20210614_1512'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'store')},
        ),
    ]
