# Generated by Django 3.0.2 on 2021-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0087_auto_20210614_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='one_c_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
