# Generated by Django 3.0.2 on 2021-06-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0088_auto_20210614_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(blank=True, null=True, related_name='_product_related_+', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_unit', to='product.Units'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
