# Generated by Django 3.0.2 on 2021-07-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0089_auto_20210618_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_product_related_+', to='product.Product'),
        ),
    ]
