# Generated by Django 3.0.2 on 2021-10-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_remove_category_cat_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.IntegerField(blank=True, default=0, help_text='Вес категории от 0 до 5. Больше вес - выше показывается', null=True),
        ),
    ]
