# Generated by Django 3.0.2 on 2021-10-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_category_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryYandexMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('shop_cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yandex_category', to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOzon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('shop_cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ozon_category', to='product.Category')),
            ],
        ),
    ]
