# Generated by Django 3.0.2 on 2021-10-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_categoryozon_categoryyandexmarket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryozon',
            options={'verbose_name': 'Категория Ozon', 'verbose_name_plural': 'Категории Ozon'},
        ),
        migrations.AlterModelOptions(
            name='categoryyandexmarket',
            options={'verbose_name': 'Категория Яндекс', 'verbose_name_plural': 'Категории Яндекс'},
        ),
    ]
