# Generated by Django 3.0.2 on 2021-11-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0102_auto_20211102_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='product.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productrating',
            name='quantity',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=5, null=True),
        ),
    ]
