# Generated by Django 3.0.2 on 2021-11-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0103_auto_20211103_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='value',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='value',
            new_name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='price_date',
        ),
        migrations.AddField(
            model_name='price',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_history', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='quantity',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=3, null=True),
        ),
    ]
