# Generated by Django 3.0.2 on 2021-11-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0104_auto_20211103_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='quantity',
            field=models.IntegerField(blank=True, default=17, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=4, null=True),
        ),
    ]
