# Generated by Django 3.0.2 on 2021-12-16 08:44

from django.db import migrations, models
import django.db.models.deletion
import product.models.models_images


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0106_auto_20211210_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_images', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='quantity',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=5, null=True),
        ),
        migrations.CreateModel(
            name='OldProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.models_images.img_path_old)),
                ('img150', models.ImageField(blank=True, null=True, upload_to=product.models.models_images.img_path_old)),
                ('img245', models.ImageField(blank=True, null=True, upload_to=product.models.models_images.img_path_old)),
                ('img500', models.ImageField(blank=True, null=True, upload_to=product.models.models_images.img_path_old)),
                ('img800', models.ImageField(blank=True, null=True, upload_to=product.models.models_images.img_path_old)),
                ('one_c_id', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.Product')),
            ],
            options={
                'verbose_name': 'Старые Фото',
                'verbose_name_plural': 'Старые Фото',
            },
        ),
    ]
