# Generated by Django 3.0.2 on 2022-11-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0110_auto_20211216_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='quantity',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
