# Generated by Django 3.0.2 on 2022-11-12 08:43

from django.db import migrations, models
import product.models.models_images


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0111_auto_20221105_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image150_webp',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.models_images.img_path_webp_tmb),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image245_webp',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.models_images.img_path_webp_tmb),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image500_webp',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.models_images.img_path_webp_tmb),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image800_webp',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.models_images.img_path_webp_tmb),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_webp',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.models_images.img_path_webp),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
