# Generated by Django 3.0.2 on 2022-11-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0113_auto_20221112_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='quantity',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
