# Generated by Django 3.0.2 on 2022-11-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0115_auto_20221112_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='quantity',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
