# Generated by Django 3.0.2 on 2020-12-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('oneCId', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=20)),
                ('catNumber', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('isDone', models.BooleanField(default=False)),
                ('signed', models.BooleanField(default=False)),
            ],
        ),
    ]
