# Generated by Django 3.0.2 on 2020-12-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasya_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rows',
            options={'verbose_name': 'Карточки в Работе'},
        ),
        migrations.AlterField(
            model_name='rows',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
