# Generated by Django 3.0.2 on 2020-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasya_interface', '0002_auto_20201209_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rows',
            name='oneCId',
            field=models.IntegerField(unique=True),
        ),
    ]
