# Generated by Django 3.0.2 on 2020-12-10 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vasya_interface', '0003_auto_20201209_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rows',
            options={'verbose_name': 'Карточка в Работе'},
        ),
        migrations.AddField(
            model_name='rows',
            name='dateChanged',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rows',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
