# Generated by Django 3.0.2 on 2020-12-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasya_interface', '0004_auto_20201210_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='rows',
            name='videoUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
