# Generated by Django 3.0.2 on 2021-04-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
