# Generated by Django 3.0.2 on 2021-04-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210418_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autouser',
            options={'verbose_name': 'Автопользователь', 'verbose_name_plural': 'Автопользователи'},
        ),
    ]
