# Generated by Django 3.0.2 on 2021-04-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210418_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autouser',
            name='userId',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
