# Generated by Django 3.0.2 on 2021-05-13 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210513_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradresses',
            name='autouser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_autouser', to='users.AutoUser'),
        ),
    ]
