# Generated by Django 3.0.2 on 2021-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210513_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradresses',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
