# Generated by Django 3.0.2 on 2021-05-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210523_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Ползователь', 'verbose_name_plural': 'Ползователи'},
        ),
    ]
