# Generated by Django 3.0.2 on 2021-05-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
