# Generated by Django 3.0.2 on 2020-10-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категоиря Блога', 'verbose_name_plural': 'Категории Блога'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Team of AngaraParts', max_length=100),
        ),
    ]
