# Generated by Django 3.0.2 on 2021-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_auto_20210423_1225'),
        ('blog', '0009_auto_20210424_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='car',
            field=models.ManyToManyField(related_name='post_car', to='product.CarModel'),
        ),
    ]
